AWSTemplateFormatVersion: 2010-09-09

Description: |
  Create static kittens carousel website

# Parameters:
  
Resources:

  WebSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP from the internet
      GroupName: web-sec-group
      SecurityGroupIngress: 
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
        - CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      Tags: 
        - Key: Name
          Value: hannakittens
      ImageId: ami-085ad6ae776d8f09c
      InstanceType: t2.micro
      KeyName: hanna-aws-first-instance
      Security-groupids:
         - Fn::GetAtt: WebSecGrp.GroupID
      UserData: 
         Fn::Base64:
         |
            #!/bin/bash -x

            yum update -y
            yum install httpd -y

            cd /var/www/html

            FOLDER="https://raw.githubusercontent.com/hanna-banana-king/my-repository/refs/heads/main/101-kittens-carousel-static-website-ec2/static-web"

            wget ${FOLDER}/index.html
            wget ${FOLDER}/cat0.jpg
            wget ${FOLDER}/cat1.jpg
            wget ${FOLDER}/cat2.jpg

            systemctl start httpd
            systemctl enable httpd

Outputs:

  WebsiteURL:
    Description: Kittens carousel website URL
    Value: !Join [ "", [ "http://", Fn::GetAtt: WebSecGrp.PublicDnsName] ] 
     
